---
driver_plugin: vagrant
platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_chef-11.2.0.box
    require_chef_omnibus: 11.4.0
  run_list:
  - recipe[apt]
suites:
- name: default
  run_list:
    - recipe[logentries-rsyslog]
    - recipe[minitest-handler]
  attributes:
    logentries:
      token: 1a2b3c
- name: no-tls
  run_list:
    - recipe[logentries-rsyslog]
    - recipe[minitest-handler]
  attributes:
    logentries:
      token: 1a2b3c
      enable_tls: false